WDP210801-11
odevpl/wdp-2108-01 pull request #21
Opened 2021-08-07 11:31 UTC by asiulijka

- Implemented favourite functionality to ProductBox
- Added visual indication if product being favourite or not
- Added flag favourite to each product in initialState.js

2021-08-08 20:09 UTC, dygus4 approved these changes

2021-08-09 06:01 UTC, odevpl requested changes
Rozwiąż konflikty

2021-08-09 15:48 UTC, asiulijka commented
> Rozwiąż konflikty

Musiałam zrobić rebasa po swojej stronie, dlatego potem użyłam komendy git push -f
Konflikty powinny być rozwiązane

2021-08-11 10:13 UTC, odevpl approved these changes

2021-08-11 10:13 UTC, merged