WDP210801-36
odevpl/wdp-2108-01 pull request #22
Opened 2021-08-07 15:30 UTC by Konrad-Jowko

Stworzyłem komponent Shop zawierający wszystkie elementy wymagane w opisie zadania. Dodałem im kolory tła, aby gołym okiem było widać ile szerokości zajmuje który element. Proszę o weryfikację :)

2021-08-09 05:50 UTC, odevpl requested changes
Hej!
Czemu skasowałeś stronę, która istnieje i zastąpiłeś ją takąsamą, tyle, że wypełnioną?
ProductList, to już istniejący komponent, w którym wrzucamy zawartość podstrony shop :P

2021-08-10 16:43 UTC, Konrad-Jowko commented
Trochę źle zinterpretowałem kod (było to przed spotkaniem) i założyłem, że ProductList jest komponentem, który pojawi się dopiero, kiedy z komponetu shop przejdziemy do produktu. Poprawię i wrzucę zmiany

2021-08-10 16:53 UTC, Konrad-Jowko commented
Zmiany zostały naniesione, proszę o weryfikację :)

2021-08-11 10:16 UTC, odevpl requested changes
Zerknij w komentarz

2021-08-11 10:16 UTC, odevpl commented on src/App.js
> +          <Route exact path={'/search/:categoryId'} component={ProductList} />
Co tu robi search?
Chyba nie o to chodziło

2021-08-11 15:22 UTC, Konrad-Jowko commented on src/App.js
> +          <Route exact path={'/search/:categoryId'} component={ProductList} />
Poprawiłem, wrzuciłem nowy Commit. Przepraszam za pomyłkę, brainfart wynikający z siedzenia nad kodem po pracy

2021-08-14 07:53 UTC, merged