WDP210801-44-NR-2
odevpl/wdp-2108-01 pull request #39
Opened 2021-08-11 21:56 UTC by dygus4

Ujednoliciłem New Furniture. Sekcja nie ulega rozdwojeniu

2021-08-12 17:36 UTC, ida-dar approved these changes
Wygląda super :).
Zasugeruję tylko użycie instrukcji switch, żeby nie powtarzać kodu.

2021-08-12 18:06 UTC, dygus4 commented
ok, dziękuje za akceptacje. Faktycznie można było użyć switch.

2021-08-12 20:32 UTC, odevpl requested changes
Hej! Kopiujesz 3 razy ten sam kod, a różnica, to tak naprawdę jedna liczba.. może by tak wrzucić tę liczbę w zmienną zależnie od typu wyświetlacza i tę samą zmienną wrzucić w sekwencję:

.slice(activePage * 2, (activePage + 1) * 2)

W tym przypadku była by to 2ka

2021-08-13 11:46 UTC, dygus4 commented
Hej, poprawiłem kod. Jeśli możesz to zobacz czy o to Ci chodziło.  Rozwiązałem jeszcze drobny konflikt

2021-08-14 08:08 UTC, odevpl requested changes
Co to za nazwy zmiennych Panie kierowniku :P

2021-08-14 08:08 UTC, odevpl commented on src/components/features/NewFurniture/NewFurniture.js
> +      abc = 'col-3';
ABC?
widthClass? columnClass
number bym zamienił na jakieś productCount?

2021-08-14 19:46 UTC, dygus4 commented on src/components/features/NewFurniture/NewFurniture.js
> +      abc = 'col-3';
Już poprawiam Panie Szefie :) Masz racje,  nazwy nie były za mądre.

2021-08-15 20:00 UTC, merged