WDP210801-48
odevpl/wdp-2108-01 pull request #41
Opened 2021-08-12 21:08 UTC by Konrad-Jowko

Wykonałem komponent Blog według wytycznych.  Nie widzę żadnych konfliktów w kodzie. Proszę o weryfikację :)

2021-08-13 18:44 UTC, Webster2020 commented on src/redux/initialState.js
> +  blog: [
Tu jest otwarty nawias kwadratowy ...

2021-08-13 18:44 UTC, Webster2020 commented on src/redux/initialState.js
> +    },
... a tu brakuje jego zamknięcia i projekt się nie odpala :)

2021-08-13 18:52 UTC, Webster2020 commented on src/components/views/Blog/Blog.js
> +          <a
Konsola krzyczy, że przydałby się tu jeszcze props 'key' :)

2021-08-13 19:08 UTC, Webster2020 commented on src/components/views/Blog/Blog.js
> +            {blog.map(article => (
Po kliknięciu w "BLOG" na stronie głównej, strona bloga nie odpala się, komunikat w konsoli: "TypeError: Cannot read property 'map' of undefined". Wygląda jakby props 'blog' nie został przekazany ze stanu aplikacji do komponentu... Jak uda Ci się to rozwikłać to daj znać co było nie tak :)

2021-08-13 19:10 UTC, Webster2020 requested changes
Hej. Duża praca włożona - szacun :) napotkałem pewne problemy - szczegóły w uwagach bezpośrednio w linijkach kodu. Powodzenia!

2021-08-16 17:59 UTC, Konrad-Jowko commented
Naniosłem zmiany, dodałem key, nawias uciekł mi podczas walki z konfliktami :) Projekt powinien już się odpalać, proszę o ponowną weryfikację :)

2021-08-17 20:03 UTC, Webster2020 approved these changes
Gra i buczy :)

2021-08-18 06:10 UTC, merged