WDP210801-51
odevpl/wdp-2108-01 pull request #46
Opened 2021-08-15 18:30 UTC by dygus4

Dodałem do formularza dwa inputy: Imię oraz Nazwisko, oraz zrobiłem walidacje formularza według instrukcji.

2021-08-16 18:24 UTC, Konrad-Jowko requested changes
Kod wygląda fajnie, schludnie i nie wywala błędów, fajna robota :) Ale w zadaniu jest informacja o tym, że gdy dane się nie zgadzają, przycisk 'Register ' nie przenosi na stronę główną - u Ciebie przenosi. Popraw to proszę a do reszty nie mam o co się czepiać :)

2021-08-16 21:02 UTC, dygus4 commented
Masz racje . Faktycznie to był błąd. Jak możesz to zerknij jeszcze raz czy teraz będzie ok ;)

2021-08-17 12:12 UTC, Konrad-Jowko requested changes
Już jest lepiej, ale widzę, że działa to tylko z hasłem, a według zadania powinno brać pod uwagę każdy input oddzielnie :)

2021-08-17 16:48 UTC, dygus4 commented
Hej, W sumie nie bardzo wiem co mogłoby być jeszcze poprawione. W momencie w którym uzupełni się dany input niezgodnie z poleceniem to pojawia się informacja  co jest niezgodne. Jak klikniesz register ( a jest niepoprawnie ) to nie przenosi. Jeśli uważasz że coś jest dalej nie tak to proszę nakieruj mnie bardziej co mam poprawić

2021-08-17 17:46 UTC, Konrad-Jowko approved these changes

2021-08-18 06:11 UTC, merged