WDP210801-62
odevpl/wdp-2108-01 pull request #48
Opened 2021-08-16 18:53 UTC by Konrad-Jowko

Dodałem sekcję Brands do podstrony shop, zgodnie z zadaniem. Proszę o weryfikację :)

2021-08-17 14:24 UTC, asiulijka commented
Wygląda ok. Strona otwiera się bez błędów.
Dodałabym małe stylowanie, aby row z Product List / Filters  był lekko odsunięty od poprzedniego kontenera (bedroom furniture). 
-> czyli wrzucić w kontener i dodać margin? albo coś w tym stylu by był podobny efekt :)
Ale ogólnie fajne i szybkie rozwiązanie zadania i czysty kod

2021-08-18 06:13 UTC, odevpl requested changes
Zasugerowano poprawki

2021-08-18 18:40 UTC, Konrad-Jowko commented
Dodałem poprawki, teraz elementy lekko odstają od Bedroom Furniture i schludnie mieszczą się w containerze, proszę o ponowną weryfikację :)

2021-08-19 11:55 UTC, asiulijka commented
teraz wygląda super :)

2021-08-19 12:00 UTC, asiulijka approved these changes

2021-08-22 20:43 UTC, merged