Add ProductPage component and its styling
odevpl/wdp-2108-01 pull request #55
Opened 2021-08-18 14:32 UTC by asiulijka

- dodanie podstrony ProductPage wg opisu zadania (podstrona miała być identyczna ze wzorem, ale niektóre ikonki na fontawesome były płatne, więc uzyłam podobnych)
- uaktualnienie sekcji Button o nowe przyciski - linki do sociamediów
- uaktualnienie sekcji settings o nowe kolory dla socialmediów

2021-08-18 16:41 UTC, Webster2020 approved these changes
Super robota :) 👍

2021-08-19 10:00 UTC, odevpl requested changes
Ticket zawiera konflikty

2021-08-19 12:29 UTC, asiulijka commented
> Ticket zawiera konflikty

Rozwiązałam konflikty

2021-08-19 15:03 UTC, Webster2020 approved these changes

2021-08-21 04:54 UTC, asiulijka commented
naprawiłam konflikty

2021-08-22 04:31 UTC, asiulijka commented
Znowu naprawilam koflikty z masterem. PROSZE O SZYBKI MERGE, bo ten PR czeka juz 4 dni.

2021-08-22 20:46 UTC, odevpl approved these changes

2021-08-22 20:46 UTC, merged