WDP210801-5 - karta produktu - przyciski stanu
odevpl/wdp-2108-01 pull request #9
Opened 2021-08-04 19:11 UTC by ida-dar

Zadanie polegało na ostylowanych stanów "ulubiony" oraz "dodany do porównania". Dodatkowo w stylach dla Buttona dodałam zmienne dla kolorów zgodnie z plikiem settings.scss. Proszę uprzejmie o weryfikację.

2021-08-05 14:10 UTC, asiulijka approved these changes
Po ściągnięciu do mnie lokalnie, strona sie odpala i wydaje sie, że spełnia wymagania zadania.

2021-08-08 07:33 UTC, odevpl requested changes
Masz dużo komentarzy po rebase w kodzie, popraw je i mergujemy :)

2021-08-08 08:47 UTC, odevpl requested changes
Popraw komentarze

2021-08-08 08:47 UTC, odevpl commented on src/components/common/Button/Button.module.scss
> +<<<<<<< HEAD
Usuń komentarz

2021-08-08 08:47 UTC, odevpl commented on src/components/common/Button/Button.module.scss
> +<<<<<<< HEAD
tu też

2021-08-09 05:42 UTC, odevpl approved these changes

2021-08-09 05:42 UTC, merged